import { redirect } from "next/navigation";
import { AccountForm } from "@/components/account-form";
import { AccountShell } from "@/components/account-shell";
import { addressAction, deleteAddressAction } from "@/app/account/actions";
import { getCurrentCustomer } from "@/lib/customers";

export const dynamic = "force-dynamic";
function AddressFields({ values }: { values?: { id?: string; fullName?: string; company?: string; address1?: string; address2?: string; city?: string; state?: string; postalCode?: string; country?: string; phone?: string; isDefault?: boolean } }) {
  return <><input type="hidden" name="addressId" value={values?.id ?? ""} /><label className="text-sm font-semibold">Full name<input required name="fullName" defaultValue={values?.fullName} className="form-input" /></label><label className="text-sm font-semibold">Company <span className="font-normal text-slate-500">(optional)</span><input name="company" defaultValue={values?.company} className="form-input" /></label><label className="text-sm font-semibold">Street address<input required name="address1" defaultValue={values?.address1} className="form-input" /></label><label className="text-sm font-semibold">Apartment or suite<input name="address2" defaultValue={values?.address2} className="form-input" /></label><label className="text-sm font-semibold">City<input required name="city" defaultValue={values?.city} className="form-input" /></label><label className="text-sm font-semibold">State<input required name="state" defaultValue={values?.state} className="form-input" /></label><label className="text-sm font-semibold">ZIP / postal code<input required name="postalCode" defaultValue={values?.postalCode} className="form-input" /></label><label className="text-sm font-semibold">Country<input required name="country" defaultValue={values?.country ?? "US"} maxLength={2} className="form-input" /></label><label className="text-sm font-semibold">Phone<input name="phone" defaultValue={values?.phone} className="form-input" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isDefault" defaultChecked={values?.isDefault} />Default shipping address</label></>;
}
export default async function AddressesPage() {
  const customer = await getCurrentCustomer();
  if (!customer) redirect("/account/sign-in");
  return <AccountShell customer={customer} title="Address book"><h1 className="font-serif text-3xl">Shipping addresses</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Editing a saved address does not change the address stored on a completed order.</p><div className="mt-6 grid gap-4">{customer.addresses.map((address) => <article key={address.id} className="account-card"><p className="font-semibold">{address.fullName}{address.isDefault ? " · Default" : ""}</p><p className="mt-2 text-sm leading-6 text-slate-600">{address.company ? `${address.company}, ` : ""}{address.address1}{address.address2 ? `, ${address.address2}` : ""}, {address.city}, {address.state} {address.postalCode}, {address.country}</p><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_auto]"><AccountForm action={addressAction} submitLabel="Save changes"><AddressFields values={address} /></AccountForm><form action={deleteAddressAction}><input type="hidden" name="addressId" value={address.id} /><button className="text-sm font-bold text-red-800">Delete</button></form></div></article>)}<article className="account-card"><h2 className="font-serif text-xl">Add address</h2><div className="mt-4"><AccountForm action={addressAction} submitLabel="Save address"><AddressFields /></AccountForm></div></article></div></AccountShell>;
}
