import Link from "next/link";
import { connection } from "next/server";
import { ArrowRight, BadgeCheck, FileCheck2, FlaskConical, ShieldCheck } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getAunevaCatalog, getCatalogCategories } from "@/lib/catalog";

const trustItems = [
  ["Made in USA", "Where supplier documentation supports it", BadgeCheck],
  ["99%+ Purity*", "Only when documented by the supplier", FlaskConical],
  ["Lot-specific COAs", "Documentation for qualifying lots", FileCheck2],
  ["Secure ordering", "Protected checkout infrastructure", ShieldCheck],
] as const;

export default async function Home() {
  await connection();
  const catalog = await getAunevaCatalog();
  const categories = getCatalogCategories(catalog.products);
  return <><SiteHeader /><main>
    <section className="hero-grid overflow-hidden"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1fr_.82fr] lg:px-8 lg:py-28"><div className="self-center"><p className="eyebrow">Established research supply</p><h1 className="mt-5 font-serif text-5xl leading-[.96] text-ink sm:text-6xl lg:text-7xl">AUNEVA <span className="text-teal">RESEARCH</span></h1><p className="mt-7 text-xl font-medium text-ink sm:text-2xl">Premium Research Products<br />Made in the USA</p><p className="mt-6 max-w-xl leading-7 text-slate-600">Carefully sourced research materials with documentation-forward quality practices and dependable fulfillment for legitimate laboratory work.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/shop" className="button-primary">Shop research products <ArrowRight size={17} /></Link><Link href="/coas-testing" className="button-secondary">View testing &amp; COAs</Link></div></div><div className="relative min-h-[370px] overflow-hidden border border-navy/10 bg-navy px-8 py-10 shadow-[0_28px_70px_rgba(7,28,45,.18)]"><div className="absolute -right-24 -top-20 h-80 w-80 rounded-full border border-white/15" /><div className="absolute -bottom-24 -left-20 h-64 w-64 rounded-full border border-teal/40" /><div className="relative flex h-full flex-col justify-between text-white"><p className="max-w-[15rem] text-xs font-semibold uppercase tracking-[.2em] text-teal-200">Documentation-led sourcing</p><div className="product-vial mx-auto"><span>A</span><i>RESEARCH</i></div><div className="border-t border-white/15 pt-5"><p className="text-sm text-slate-300">Research catalog</p><p className="text-lg font-semibold">Built for traceability</p></div></div></div></div></section>
    <section className="border-y border-navy/10 bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-navy/10 px-6 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4 lg:px-8">{trustItems.map(([label, note, Icon]) => <div className="flex gap-3 py-6 sm:px-5" key={label}><Icon className="mt-1 shrink-0 text-teal" size={19} /><div><p className="text-sm font-bold uppercase tracking-[.1em]">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{note}</p></div></div>)}</div></section>
    <section className="section-shell"><div className="section-heading"><div><p className="eyebrow">Research catalog</p><h2>Shop by category</h2></div><Link href="/shop" className="text-link">View all products <ArrowRight size={16} /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <Link key={category.slug} href={`/shop/category/${category.slug}`} className="group border border-navy/10 bg-white p-6 shadow-sm hover:border-teal"><p className="text-sm font-bold text-teal">0{index + 1}</p><h3 className="mt-12 font-serif text-2xl text-ink group-hover:text-teal">{category.name}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{category.description}</p><p className="mt-6 text-xs font-bold uppercase tracking-[.1em] text-navy">{category.productCount} products</p></Link>)}</div><Link href="/shop" className="button-primary mt-8">View all products <ArrowRight size={17} /></Link></section>
    <section className="bg-navy py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow text-teal-200">Sourcing &amp; fulfillment</p><h2 className="mt-4 max-w-lg font-serif text-4xl leading-tight sm:text-5xl text-white">Proudly made in the USA</h2></div><p className="border-l border-teal/60 pl-6 leading-7 text-slate-300">Qualifying products supplied through our manufacturing and fulfillment partner are manufactured in the United States. Auneva displays Made in USA designations only where supplier data and supporting documentation substantiate the claim.</p></div></section>
    <section className="section-shell grid gap-12 lg:grid-cols-[1fr_1.1fr]"><div><p className="eyebrow">Quality &amp; testing</p><h2 className="mt-4">Evidence before assertion</h2><p className="mt-5 max-w-md leading-7 text-slate-600">Our catalog is designed to associate applicable lots with the documentation used to substantiate product information. We do not publish specific purity percentages or testing results without supplier support.</p><Link href="/coas-testing" className="mt-7 inline-flex items-center gap-2 font-semibold text-navy hover:text-teal">Explore COAs &amp; testing <ArrowRight size={17} /></Link></div><div className="grid gap-3 sm:grid-cols-2">{["Lot-specific testing", "HPLC purity testing", "Mass spectrometry identity verification", "Certificates of Analysis"].map((item, index) => <div key={item} className="border border-navy/10 bg-white p-6 shadow-sm"><span className="text-sm font-bold text-teal">0{index + 1}</span><p className="mt-8 font-serif text-xl">{item}</p><p className="mt-3 text-sm leading-6 text-slate-500">Available for review where provided and applicable to a qualifying product lot.</p></div>)}</div></section>
    <section className="bg-slate-100 py-20"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="eyebrow">A clear process</p><h2 className="mt-4">Research ordering, simplified</h2><div className="mt-11 grid gap-8 md:grid-cols-3">{[["01", "Browse Research Products", "Review available product and documentation details."], ["02", "Place Your Order", "Submit your order through our secure ordering process."], ["03", "Secure Fulfillment & Tracking", "Receive fulfillment updates and available tracking information."]].map(([step, title, text]) => <div key={step} className="border-t-2 border-teal pt-5"><p className="text-sm font-bold text-teal">{step}</p><h3 className="mt-5 font-serif text-2xl">{title}</h3><p className="mt-3 max-w-xs leading-7 text-slate-600">{text}</p></div>)}</div></div></section>
    <section className="section-shell"><div className="grid gap-10 border-y border-navy/10 py-16 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Research use</p><h2 className="mt-4">Designed for legitimate laboratory work</h2></div><p className="border-l-2 border-teal pl-6 text-xl leading-8">Products offered through Auneva Research are intended exclusively for legitimate laboratory and research purposes and are not intended for human or veterinary consumption.</p></div></section>
    <section className="bg-teal-50 py-20"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow">Common questions</p><h2 className="mt-4">Information that stays clear</h2></div><div className="space-y-4">{["How are product details and documents presented?", "Where can I find Certificates of Analysis?", "How do I track an order?"].map((question) => <Link href="/faq" className="flex items-center justify-between border-b border-navy/15 py-4 font-medium hover:text-teal" key={question}>{question}<ArrowRight size={18} /></Link>)}</div></div></section>
    <section className="bg-ink py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-6 lg:flex-row lg:items-end lg:px-8"><div><p className="eyebrow text-teal-200">Stay informed</p><h2 className="mt-3 font-serif text-4xl text-white">Research updates, thoughtfully sent.</h2><p className="mt-3 max-w-xl text-slate-300">For catalog, documentation and fulfillment updates. Contact our team for order support or business inquiries.</p></div><Link href="/contact" className="button-light">Contact Auneva <ArrowRight size={17} /></Link></div></section>
  </main><SiteFooter /></>;
}
