"use client";

import Link from "next/link";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { ProductPrice } from "@/components/product-price";

const money = (value: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value);

export function CartPage() {
  const cart = useCart();
  if (!cart.pricingReady) return <div className="py-20 text-center"><p className="font-serif text-3xl text-ink">Refreshing current prices</p></div>;
  if (cart.pricingError) return <div role="alert" className="border border-red-200 bg-red-50 p-5 text-red-950">Current catalog pricing is unavailable. Refresh the page before proceeding to checkout.</div>;
  if (!cart.lines.length) return <div className="py-20 text-center"><p className="font-serif text-4xl text-ink">Your cart is empty</p><p className="mt-3 text-slate-600">Browse our catalog to add research products.</p><Link href="/shop" className="button-primary mt-7">Shop research products</Link></div>;
  return <div className="grid gap-10 lg:grid-cols-[1fr_22rem]"><div className="divide-y divide-navy/10 border-y border-navy/10">{cart.lines.map((line) => <div key={line.id} className="flex gap-5 py-5"><div className="flex h-20 w-20 shrink-0 items-center justify-center bg-teal-50 font-serif text-xl text-navy">A.</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-4"><div><p className="font-semibold text-ink">{line.name}</p><p className="mt-1 text-sm text-slate-500">{line.specification}</p></div><button onClick={() => cart.remove(line.id)} aria-label={`Remove ${line.name}`} className="h-fit text-slate-500 hover:text-red-700"><Trash2 size={17} /></button></div><div className="mt-4 flex items-center justify-between"><div className="flex items-center border border-navy/15"><button onClick={() => cart.setQuantity(line.id, line.quantity - 1)} className="p-2" aria-label={`Remove one ${line.name}`}><Minus size={14} /></button><span className="min-w-8 text-center text-sm">{line.quantity}</span><button onClick={() => cart.setQuantity(line.id, line.quantity + 1)} className="p-2" aria-label={`Add one ${line.name}`}><Plus size={14} /></button></div><ProductPrice retailPrice={line.retailPrice} salePrice={line.salePrice} saleDiscountPercent={line.saleDiscountPercent} currency={cart.currency} quantity={line.quantity} className="justify-end text-right" /></div></div></div>)}</div><aside className="h-fit border border-navy/10 bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl">Order summary</h2><div className="mt-6 space-y-3 border-y border-navy/10 py-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(cart.subtotal, cart.currency)}</span></div><div className="flex justify-between text-slate-500"><span>Shipping estimate</span><span>At checkout</span></div><div className="flex justify-between text-slate-500"><span>Taxes</span><span>When applicable</span></div></div><div className="mt-5 flex justify-between font-semibold"><span>Order total</span><span>{money(cart.subtotal, cart.currency)} + shipping</span></div><Link href="/checkout" className="button-primary mt-6 w-full">Proceed to checkout</Link></aside></div>;
}