import Link from "next/link";
import type { Metadata } from "next";
import { Search } from "lucide-react";
import { AddToCartButton } from "@/components/add-to-cart-button";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getAunevaCatalog } from "@/lib/catalog";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Research Products", description: "Browse Auneva Research products with documentation-forward catalog information.", alternates: { canonical: "/shop" } };

export default async function ShopPage({ searchParams }: { searchParams: Promise<{ q?: string; format?: string; sort?: string }> }) {
  const { q = "", format = "", sort = "featured" } = await searchParams;
  const snapshot = await getAunevaCatalog();
  const normalizedQuery = q.trim().toLowerCase();
  const formats = [...new Set(snapshot.products.map((product) => product.format))];
  const products = snapshot.products.filter((product) => (!format || product.format === format) && (!normalizedQuery || `${product.name} ${product.specification} ${product.sku ?? ""}`.toLowerCase().includes(normalizedQuery))).sort((first, second) => sort === "price-low" ? first.retailPrice - second.retailPrice : sort === "price-high" ? second.retailPrice - first.retailPrice : sort === "name" ? first.name.localeCompare(second.name) : Number(second.featured) - Number(first.featured));
  return <><SiteHeader /><main><section className="bg-[#eaf6f5] py-16"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="eyebrow">Research catalog</p><h1 className="mt-4 font-serif text-5xl text-ink">Research products</h1><p className="mt-5 max-w-2xl leading-7 text-slate-600">Catalog information is synchronized from our fulfillment partner. Product availability and supporting records are shown only where supplier data supports them.</p></div></section><section className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><form className="grid gap-3 border-b border-navy/10 pb-8 md:grid-cols-[1fr_10rem_10rem_auto]"><label className="relative"><span className="sr-only">Search research products</span><Search className="absolute left-3 top-3 text-slate-500" size={17} /><input name="q" defaultValue={q} placeholder="Search catalog" className="h-11 w-full border border-navy/15 bg-white pl-10 pr-3 text-sm outline-teal" /></label><select name="format" defaultValue={format} className="h-11 border border-navy/15 bg-white px-3 text-sm"><option value="">All formats</option>{formats.map((item) => <option key={item} value={item}>{item}</option>)}</select><select name="sort" defaultValue={sort} className="h-11 border border-navy/15 bg-white px-3 text-sm"><option value="featured">Featured</option><option value="name">Name</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select><button className="button-primary">Apply</button></form>{snapshot.error ? <div className="py-20 text-center"><p className="font-serif text-3xl text-ink">Catalog temporarily unavailable</p><p className="mt-3 text-slate-600">Please check back shortly. The storefront remains available while supplier catalog data is refreshed.</p></div> : products.length === 0 ? <div className="py-20 text-center"><p className="font-serif text-3xl text-ink">No matching products</p><p className="mt-3 text-slate-600">Try adjusting your search or filters.</p></div> : <div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <article key={product.id} className="border border-navy/10 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-teal">{product.format}</p><h2 className="mt-2 font-serif text-2xl text-ink">{product.name}</h2><p className="mt-2 text-sm text-slate-500">{product.specification}</p><p className="mt-5 text-xl font-semibold text-navy">{new Intl.NumberFormat("en-US", { style: "currency", currency: product.currency }).format(product.retailPrice)}</p><p className="mt-2 text-xs text-slate-500">Availability: supplier confirmation required</p><div className="mt-6 grid grid-cols-2 gap-3"><Link href={`/product/${product.slug}`} className="button-secondary">Details</Link><AddToCartButton product={product} /></div></article>)}</div>}</section></main><SiteFooter /></>;
}