import Link from "next/link";
import type { Metadata } from "next";
import { Search } from "lucide-react";
import { CatalogProductCard } from "@/components/catalog-product-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getAunevaCatalog, getCatalogCategories } from "@/lib/catalog";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Research Products", description: "Browse Auneva Research products with documentation-forward catalog information.", alternates: { canonical: "/shop" } };

export default async function ShopPage({ searchParams }: { searchParams: Promise<{ q?: string; format?: string; sort?: string }> }) {
  const { q = "", format = "", sort = "featured" } = await searchParams;
  const snapshot = await getAunevaCatalog();
  const normalizedQuery = q.trim().toLowerCase();
  const categories = getCatalogCategories(snapshot.products);
  const products = snapshot.products.filter((product) => (!format || product.format === format) && (!normalizedQuery || `${product.name} ${product.specification} ${product.sku ?? ""}`.toLowerCase().includes(normalizedQuery))).sort((first, second) => sort === "price-low" ? (first.salePrice ?? first.retailPrice) - (second.salePrice ?? second.retailPrice) : sort === "price-high" ? (second.salePrice ?? second.retailPrice) - (first.salePrice ?? first.retailPrice) : sort === "name" ? first.name.localeCompare(second.name) : Number(second.featured) - Number(first.featured));

  return <><SiteHeader /><main><section className="bg-[#eaf6f5] py-16"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="eyebrow">Research catalog</p><h1 className="mt-4 font-serif text-5xl text-ink">Shop all products</h1><p className="mt-5 max-w-2xl leading-7 text-slate-600">{snapshot.products.length} available research products, synchronized from our fulfillment partner.</p></div></section><section className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div className="mb-6 flex flex-wrap gap-2">{categories.map((category) => <Link key={category.slug} href={`/shop/category/${category.slug}`} className="border border-navy/15 px-3 py-2 text-xs font-bold uppercase tracking-[.08em] text-navy hover:border-teal hover:text-teal">{category.name} ({category.productCount})</Link>)}</div><form className="grid gap-3 border-b border-navy/10 pb-8 md:grid-cols-[1fr_12rem_10rem_auto]"><label className="relative"><span className="sr-only">Search research products</span><Search className="absolute left-3 top-3 text-slate-500" size={17} /><input name="q" defaultValue={q} placeholder="Search catalog" className="h-11 w-full border border-navy/15 bg-white pl-10 pr-3 text-sm outline-teal" /></label><select name="format" defaultValue={format} className="h-11 border border-navy/15 bg-white px-3 text-sm"><option value="">All categories</option>{categories.map((category) => <option key={category.slug} value={category.format}>{category.name}</option>)}</select><select name="sort" defaultValue={sort} className="h-11 border border-navy/15 bg-white px-3 text-sm"><option value="featured">Featured</option><option value="name">Name</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select><button className="button-primary">Apply</button></form><p className="mt-6 text-sm text-slate-500">Showing {products.length} of {snapshot.products.length} products</p>{snapshot.error ? <div className="py-20 text-center"><p className="font-serif text-3xl text-ink">Catalog temporarily unavailable</p><p className="mt-3 text-slate-600">Please try again shortly.</p></div> : <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <CatalogProductCard key={product.id} product={product} />)}</div>}</section></main><SiteFooter /></>;
}